// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5UHcFpQsWInmrcMAOE3VErXAtYCGyR0',
    appId: '1:432824759061:android:3cf8bc499c29a880e3ef1c',
    messagingSenderId: '432824759061',
    projectId: 'eirs-23f58',
    storageBucket: 'eirs-23f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR-Cw-05r1mSyfoT3-BQ6YmrpxRgm9oow',
    appId: '1:432824759061:ios:22528d32f40c510fe3ef1c',
    messagingSenderId: '432824759061',
    projectId: 'eirs-23f58',
    storageBucket: 'eirs-23f58.firebasestorage.app',
    iosBundleId: 'com.example.gargaarApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSrt19iFXqYfkXG7aiOhCtuCQ47g1VGg',
    appId: '1:432824759061:web:1069ec51cc670469e3ef1c',
    messagingSenderId: '432824759061',
    projectId: 'eirs-23f58',
    authDomain: 'eirs-23f58.firebaseapp.com',
    storageBucket: 'eirs-23f58.firebasestorage.app',
    measurementId: 'G-2SXGC3RJY3',
  );
}
